### ISSUE TITLE
Issue Pulling in Filings for Current Quarter

### ISSUE THREAD

**Issue by bcicc** [tylerjthomas9/ScrapeSEC.jl#24]
I tried pulling in filings for 2024 on October 1st, 2024 and got a 403 from the [SEC](https://www.sec.gov/Archives/edgar/full-index/2024/QTR4/master.zip). Not sure if this only happens on the first day of the quarter, but since the current quarter is 4 it is included in the requests.

**Comment by tylerjthomas9** [comment]
Thank you for reporting this.
